### ISSUE TITLE
Default config problem with wlan config and older Micropython version

### ISSUE THREAD

**Issue by rroemhild** [microhomie/micropython-homie#4]
Initialization of homie class fails because of the default configuration and missing `config()` method from `network.WLAN` on older MicroPython versions:

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "/flash/lib/homie/__init__.py", line 31, in <module>
AttributeError: 'WLAN' object has no attribute 'config'
MicroPython v1.8.6-849-fcbbfe3 on 2018-01-03; FiPy with ESP32
```

Possible solution could be to move the default configuration to a separate file i.e. `settings.py` and import this file.

**Comment by kinkerl** [comment]
Hm. We can just catch the error in this line? 
https://github.com/microhomie/micropython-homie/blob/master/homie/__init__.py#L31
Whats the benefit to move in to `settings.py` ?

**Comment by kinkerl** [comment]
BTW, I am still not happy with the refactor branch but this is solved there because we have the same problem on "UNIX mode". Maybe this is a solution?`
https://github.com/microhomie/micropython-homie/blob/feature/refactor/homie/__init__.py

**Comment by kinkerl** [comment]
max fixed with https://github.com/microhomie/micropython-homie/pull/6 ?

**Comment by kinkerl** [comment]
fixed
